### ISSUE TITLE
integration with slack not working

### ISSUE THREAD

**Issue by byahia** [jfrog/partner-integrations#54]
Hi,
The documentaiton seems to be outdated: https://github.com/jfrog/partner-integrations/tree/main/Slack/Platform
There is no an "integration" menue under Administartion -> security.
can you update the documentation with the procedure to correctly set up a notification with slack using the slack app https://emobg.slack.com/apps/A02C54FAX9B-jfrog-artifactory-and-xray?utm_source=in-prod&utm_medium=inprod-btn_app_install-index-click&tab=more_info

**Comment by Dattax** [comment]
Thanks! We have updated the documentation. Please email me if you have any other issues: deepd@jfrog.com.
