### ISSUE TITLE
Xray Violations notification

### ISSUE THREAD

**Issue by mazay** [jfrog/partner-integrations#56]
The Xray violations notification is missing the highest severity in the list. I.e. if an artefact had critical severity violations the slack notification will contain violations from high to low/unknown, if there were no critical violations the notification contains medium and lower severity. Checking the related watches in Jfrog UI shows all the severities.

There seem to be some issue with skipping first element in the list when generating the message payload.

**This is the critical issue as dev teams might be misinformed about the violations and may end up pushing vulnerable code to production.**

**Comment by alexhung** [comment]
@mazay Which integration is this issue for?

Which version of Xray are you running? This issue is fixed in 3.44.1. See [release notes](https://www.jfrog.com/confluence/display/JFROG/Xray+Release+Notes#XrayReleaseNotes-Xray3.44.1).

**Comment by mazay** [comment]
@alexhung how would one check that in the cloud hosted Jfrog? Also if it's different - do I have a control over the upgrade procedure?

**Comment by alexhung** [comment]
@mazay You need to contact support team to check the version your SaaS instance(s) are running, as well as request for upgrade if necessary. Generally SaaS version is automatically updated to latest but I believe that's applied on a rolling update basis so there may be delay.

**Comment by mazay** [comment]
thanks, I'll check with support
